In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
import glob
from tqdm import tqdm

In [2]:
from google.colab import drive
drive.mount('/content/Drive')

Mounted at /content/Drive


In [ ]:
image_path = '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00000_00002.ppm'
image = cv2.imread(image_path)
image_np = np.asarray(image)
print(image_np.shape)


(30, 30, 3)


In [ ]:
folder_1_path = '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000'
img_1_paths = os.listdir(folder_1_path)


In [ ]:
print((img_1_paths))

['00001_00000.ppm', '00001_00009.ppm', '00000_00018.ppm', '00001_00027.ppm', '00000_00027.ppm', '00000_00005.ppm', '00001_00005.ppm', '00000_00021.ppm', '00000_00004.ppm', '00002_00010.ppm', '00002_00008.ppm', '00001_00020.ppm', '00001_00028.ppm', '00001_00023.ppm', '00001_00004.ppm', '00000_00023.ppm', '00000_00009.ppm', '00000_00003.ppm', '00001_00018.ppm', '00002_00011.ppm', '00002_00002.ppm', '00001_00013.ppm', '00000_00011.ppm', '00000_00000.ppm', '00001_00017.ppm', '00002_00004.ppm', '00001_00022.ppm', '00001_00012.ppm', '00001_00019.ppm', '00000_00024.ppm', '00001_00029.ppm', '00002_00016.ppm', '00001_00024.ppm', '00001_00026.ppm', '00002_00013.ppm', '00002_00012.ppm', '00000_00017.ppm', '00000_00028.ppm', '00002_00005.ppm', '00002_00001.ppm', '00001_00011.ppm', '00002_00014.ppm', '00000_00022.ppm', '00002_00017.ppm', '00000_00019.ppm', '00001_00002.ppm', '00000_00007.ppm', '00001_00025.ppm', '00000_00026.ppm', '00002_00009.ppm', '00001_00008.ppm', '00002_00007.ppm', '00001_0000

In [ ]:
img_1_paths.remove('GT-00000.csv')

In [ ]:
image_1_folder_path = '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000'
full_path_image_1 = []
for path in img_1_paths:
  full_path = os.path.join(image_1_folder_path,path)
  full_path_image_1.append(full_path)

In [ ]:
print((full_path_image_1))

['/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00001_00000.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00001_00009.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00000_00018.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00001_00027.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00000_00027.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00000_00005.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00001_00005.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00000_00021.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00000_00004.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00002_00010.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00002_00008.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00001_00020.ppm', '/content/Drive/MyDrive/GTSRB/Final_Training/Images/00000/00001_00028.ppm', '/content/D

In [ ]:
# trial 1
arr = np.array([[1,1,1],[2,2,2],[3,3,3]])
np.random.shuffle(arr)
print(arr)

x = '0-0.ppm'
if '.ppm' in x:
  print('yes')

[[2 2 2]
 [1 1 1]
 [3 3 3]]
yes


In [ ]:
gt_0 = np.array(0)
print(type(gt_0))

<class 'numpy.ndarray'>


In [ ]:
data_image_1 = []
for path in full_path_image_1:
  image = cv2.imread(path)
  image_np = np.asarray(image)
  image_final = np.resize(image_np,(30,30,3))
  data_image_1.append([image_final,gt_0])

In [ ]:
print(data_image_1[0][1])

[0]


In [ ]:
image_data_1_np = np.asarray(data_image_1)
print(image_data_1_np[0][1])

[0]


/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [3]:
# Get all images from the folder and put their names in a list
def get_all_files_in_list(folder_path):
  image_paths = os.listdir(folder_path)
  return(image_paths)

In [4]:
# All the folders have a .csv file in the end. We need to remove that file, as we are manually setting the ground truth
def remove_csv_file(path_list):
  for path in path_list:
    if '.csv' in path:
      path_list.remove(path)
      return path_list

In [5]:
# The list only has individual file names. We need to attach the folder path to make the full path
def get_full_image_path(folder_path, path_list):
  full_path_image_list = []
  for path in path_list:
    full_path = os.path.join(folder_path,path)
    full_path_image_list.append(full_path) 
  return full_path_image_list

In [6]:
# Manually setting the ground truth class
def make_gt_array(class_number):
  assert type(class_number) == int
  gt = np.array(class_number)
  return gt

In [7]:
# Converting the .ppm images into numpy arrays and put all of them in a list
def convert_to_data(full_path_list, class_number):
  data = []
  gt = make_gt_array(class_number)
  for path in full_path_list:
    image = cv2.imread(path)
    image_np = np.asarray(image)
    image_final = np.resize(image_np,(30,30,3))
    data.append([image_final,gt])
  return data

In [8]:
# Coverting the list to a numpy array
def convert_to_np(image_data_list):
  data_np = np.asarray(image_data_list)
  return data_np

In [9]:
main_folders_list = os.listdir('/content/Drive/MyDrive/GTSRB/Final_Training/Images')
folders_full_paths = get_full_image_path('/content/Drive/MyDrive/GTSRB/Final_Training/Images',main_folders_list)

In [ ]:
# trial 2
example_path = folders_full_paths[0]
split = os.path.split(example_path)
int(split[1])

37

In [10]:
# Get class number directly from the path
def get_class_num(full_folder_path):
  split = os.path.split(full_folder_path)
  class_num = int(split[1])
  return class_num

In [11]:
# Get the numpy array of individual classes
def get_array(folder_path):
  class_number = get_class_num(folder_path)
  print(class_number)
  image_names = get_all_files_in_list(folder_path)
  image_names = remove_csv_file(image_names)
  image_paths = get_full_image_path(folder_path, image_names)
  data_list = convert_to_data(image_paths, class_number)
  data_np = convert_to_np(data_list)
  return data_np


In [ ]:
# Trial 3
x = get_array(example_path)

/usr/local/lib/python3.7/dist-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [ ]:
# Trial 4
arr_1 = np.arange(4).reshape(2,2)
arr_2 = np.arange(4).reshape(2,2)
arr_3 = np.array([[3],[3]])
arr = np.concatenate((arr_1, arr_2))
arr


array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [ ]:
array_list = []
for path in tqdm(folders_full_paths):
  x = get_array(path)
  array_list.append(x)

In [23]:
len(array_list[4])

2070

In [78]:
# Make whole data in the form of a numpy array
arr_np = array_list[0]
for i in range(1,len(array_list)):
  arr_np = np.concatenate((arr_np,array_list[i]))

In [81]:
arr_np.shape

(39209, 2)

In [80]:
np.random.shuffle(arr_np)


In [82]:
train = arr_np[:35289]
test = arr_np[35289:]

In [84]:
test.shape

(3920, 2)

In [86]:
X_train = train[0][0]
for i in tqdm(range(1,len(train))):
  X_train = np.concatenate((X_train,train[i][0]))
X_train = X_train.reshape(35289,30,30,3)
X_train.shape

100%|██████████| 35288/35288 [10:22<00:00, 56.71it/s]


(35289, 30, 30, 3)

In [89]:
X_test = test[0][0]
for i in tqdm(range(1,len(test))):
  X_test = np.concatenate((X_test, test[i][0]))
X_test = X_test.reshape(3920,30,30,3)
X_test.shape

100%|██████████| 3919/3919 [00:04<00:00, 836.18it/s]


(3920, 30, 30, 3)

In [95]:
Y_train = np.array(train[0][1])
for i in tqdm(range(1,len(train))):
  Y_train = np.concatenate((Y_train, np.array(train[i][1])))
Y_train = Y_train.reshape(35289,1)
Y_train.shape

  0%|          | 0/35288 [00:00<?, ?it/s]


ValueError: ignored

In [100]:
# trial
a = np.array(1)
b = np.array(2)
c = np.append(a,b)
c

array([1, 2])

In [101]:
y_train_list = []
for i in tqdm(range(len(train))):
  y_train_list.append(train[i][1])

len(y_train_list)

100%|██████████| 35289/35289 [00:00<00:00, 994241.91it/s]


35289

In [103]:
y_train = np.asarray(y_train_list)
y_train = y_train.reshape(35289,1)
y_train.shape

(35289, 1)

In [104]:
y_train

array([[ 9],
       [11],
       [13],
       ...,
       [ 5],
       [ 2],
       [ 5]])

In [105]:
y_test_list = []
for i in tqdm(range(len(test))):
  y_test_list.append(test[i][1])

len(y_test_list)

100%|██████████| 3920/3920 [00:00<00:00, 436697.79it/s]


3920

In [106]:
y_test = np.asarray(y_test_list)
y_test = y_test.reshape(3920,1)
y_test.shape

(3920, 1)

In [108]:
np.save('/content/Drive/MyDrive/GTSRB/X_train', X_train)
np.save('/content/Drive/MyDrive/GTSRB/X_test', X_test)
np.save('/content/Drive/MyDrive/GTSRB/y_train', y_train)
np.save('/content/Drive/MyDrive/GTSRB/y_test', y_test)